### ISSUE TITLE
Deployment Issue

### ISSUE THREAD

**Issue by NamrataAnand** [eventuate-examples/eventuate-examples-java-customers-and-orders#29]
I am adding/creating new API for fetching information of all customers and for that I have added new method getAllCustomers() in CustomerOrderHistoryController Class. Build is successful but after deployment the new API is giving 404. Is there any configuration I am missing out on?

command used to build -./gradlew assemble -P eventuateDriver=local
Command used for docker - docker-compose -f docker-compose-eventuate-local-mysql.yml up

**Comment by cer** [comment]
Try adding a --build argument:

```
docker-compose -f docker-compose-eventuate-local-mysql.yml up --build
```

**Comment by NamrataAnand** [comment]
It worked. Thanks for Replying.
