### ISSUE TITLE
Add code doc

### ISSUE THREAD

**Issue by BernhardBln** [eventuate-examples/eventuate-examples-java-customers-and-orders#32]
In the customer event handler, it checks if there is enough credit and then makes the reservation, without further synchronisation or locking.

I assume this works because with Kafka, the consumer of the events for a certain customer would always apply them in order and not in concurrency.

Would that be worth a java doc in the customer event consumer's reserve credit method?

**Comment by cer** [comment]
The [Eventuate Local update operation](https://github.com/eventuate-examples/eventuate-examples-java-customers-and-orders/blob/4bcd5510f3c80b41e394c3104d7a4ebe0f56a1f8/customers-service/src/main/java/net/chrisrichardson/eventstore/examples/customersandorders/customersservice/backend/CustomerWorkflow.java#L23) implements optimistic locking:
